# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171106_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Pre_tips',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Tips',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Total',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
